import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { MainNavigation } from "./components/ui/MainNavigation";
import { Footer } from "./components/ui/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${roboto.variable} antialiased flex flex-col min-h-screen w-full max-w-screen-xl mx-auto`}
        >
          <MainNavigation />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
